rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  # Effort Controllers ---------------------------------------
  joint_base_mid_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint_base_mid
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_mid_top_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint_mid_top
    pid: {p: 100.0, i: 0.01, d: 10.0}
  