controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    
    #position_controllers:
     # type: position_controllers/JointGroupPositionController
     
    #forward_command_controller:
      #type: forward_command_controller/ForwardCommandController
  


    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controllers:
  ros__parameters:
    joints:
      - joint_base_mid
      - joint_mid_top
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

#position_controllers:
 # ros__parameters:
  #  joints:
   #   - joint_base_mid
    #  - joint_mid_top
   # command_interfaces:
    #  - position
    #state_interfaces:
     # - position
     # - velocity


#forward_command_controller:
  #ros__parameters:
    #joints:
     # - joint_base_mid
     # - joint_mid_top
    #interface_name: position
    #command_interfaces:
    #  - position
    #state_interfaces:
    #  - position
    #  - velocity


    
